const config = {
  baseUrl: "https://test.erp.craftschoolship.com/jsonrpc",
  database: "bitnami_odoo",
  username: process.env.EXPO_PUBLIC_USERNAME,
  password: process.env.EXPO_PUBLIC_PASSWORD,
  model: {
    accountMove: "account.move",
    accountMoveLine: "account.move.line",
    accountTax: "account.tax",
    attendance: "op.attendance.line",
    calendar: "calendar.event",
    calendarAttendee: "calendar.attendee",
    craftInvoice: "craft.invoice",
    craftInstallmentLines: "craft.installment.lines",
    craftSession: "craft.session",
    craftStudent: "craft.student",
    craftParentChildLine: "craft.parent.child.line",
    // groups: "op.batch",
    groups: "craft.class",
    opActivity: "op.activity",
    opCourse: "op.course",
    opParents: "op.parent",
    opSession: "op.session",
    opStudent: "op.student",
    parents: "craft.parent",
    partner: "res.partner",
    productTemplate: "product.template",
    resCurrency: "res.currency",
    resGroups: "res.groups",
    saleOrder: "sale.order",
    // parents: "craft.parent",
    teachers: "craft.teacher",
    users: "res.users",
  },
};

export default config;
